
# [WLAN][SHARP] Customize Start
#                 2015.08.21 register resume function to workqueue to compress
#                 system resuming time. 
ccflags-y += -D SH_WIFI_CUSTOMIZE
# [WLAN][SHARP] Customize End

obj-$(CONFIG_PCI_MSM) += pci-msm.o
