#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_FPRINT_SYSFS)		+= shfpsensor_sysfs.o
obj-$(CONFIG_SENSORS_FPRINT_VFS61XX)	+= shfpsensor.o
